---
# This playbook contains nginx install plays for all "webserver" nodes

- name: install nginx on non-RedHat systems (without yum package manager)
  package:
    name: nginx
    state: present
  when: ansible_facts['os_family'] != "RedHat"

- name: install epel repo on RedHat systems (with yum package manager)
  yum:
    name: epel-release
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: install nginx on RedHat systems (with yum package manager)
  yum:
    name: nginx
    state: present
    enablerepo: epel
    update_cache: yes
  when: ansible_facts['os_family'] == "RedHat"
