---
# This playbook contains openssl config plays for all "webserver" nodes

- name: update openssl config file
  vars:
    cipher_suites: "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256"
    options: "ServerPreference"
  template:
    src: openssl.cnf.j2
    dest: /etc/ssl/openssl.cnf
  notify:
    - restart nginx
    - retart gunicorn