---
# This playbook contains site instance file upload plays for all "webserver" nodes

- name: Upload site instance-specific files to server
  copy:
    src: "{{ website_files_directory_name }}/"
    dest: "/home/{{ zaphod_user }}/zaphod/venv/var/zaphod-instance/"
    mode: "770"
    owner: "{{ zaphod_user }}"
    group: "{{ nginx_user }}"
  notify:
    - restart gunicorn
    - restart nginx
    - chown venv to zaphod_user
    - chmod zaphod_user's home directory
