---
# This playbook contains zaphod initialization plays for all "webserver" nodes

- name: initialize flask db
  environment:
    FLASK_APP: zaphod
  command:
    chdir: "/home/{{ zaphod_user }}/zaphod/"
    cmd: ./venv/bin/python3 -m flask init-db
  register: command_result
  failed_when: '"Initialized the database." not in command_result.stdout'
  notify:
    - restart gunicorn
    - restart nginx
    - chown venv to zaphod_user
    - chmod zaphod_user's home directory
